project_id = "hjemyrrniopogkbbewnm"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[functions.bluesky-post]
verify_jwt = true

[storage]
enabled = true