// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcpwfaxslveomvngwtvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjcHdmYXhzbHZlb212bmd3dHZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDYxOTIsImV4cCI6MjA2MDkyMjE5Mn0.n3o7r3vSF0q0WWmdfm1Z1IPUnimBEgzT_HHZKwCBOVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});